import mongoose from "mongoose";
import env from "../src/config/env.js";
import User from "../src/models/User.js";
import Category from "../src/models/Category.js";
import Collection from "../src/models/Collection.js";
import Product from "../src/models/Product.js";
import Banner from "../src/models/Banner.js";
import FAQ from "../src/models/FAQ.js";
import Testimonial from "../src/models/Testimonial.js";
import CMSPage from "../src/models/CMSPage.js";
import Coupon from "../src/models/Coupon.js";
import SiteSettings from "../src/models/SiteSettings.js";
import { slugify } from "../src/utils/helpers.js";

const img = (n) => `/uploads/seed/${n}.jpg`;

const categories = [
  {
    name: "New Arrivals",
    slug: "new-arrivals",
    image: "necklace-earring-set",
    circle: true,
    subs: [],
  },
  {
    name: "God / Deity Jewellery",
    slug: "god-jewellery",
    image: "lakshmi-kasu-haram",
    circle: true,
    home: false,
    subs: ["Lakshmi Haram", "Deity Pendant", "Kasu Mala"],
  },
  {
    name: "Bharatnatyam Jewellery",
    slug: "bharatnatyam-jewellery",
    image: "vaddanam-waist",
    circle: true,
    home: true,
    subs: ["Vaddanam", "Full Set", "Waist Belt"],
  },
  {
    name: "Jadau Kundan Jewellery",
    slug: "jadau-kundan-jewellery",
    image: "pink-choker",
    circle: true,
    home: true,
    subs: ["Kundan Choker", "Kundan Set", "Polki"],
  },
  {
    name: "Varalakshmi Items",
    slug: "varalakshmi-items",
    image: "temple-necklace",
    circle: true,
    home: true,
    subs: ["Pooja Set", "Face Mask", "Jewellery Set"],
  },
  {
    name: "Necklaces",
    slug: "necklaces",
    image: "antique-necklace",
    subs: ["Necklace", "Pendant Set", "Choker", "Long Haram"],
  },
  {
    name: "Earrings",
    slug: "earrings",
    image: "jhumka-pair",
    subs: ["Jhumkas", "Chandbali", "Studs", "Drops"],
  },
  {
    name: "Pendants",
    slug: "pendants",
    image: "ganesha-pendant",
    subs: ["Deity Pendant", "Diamond Look", "Fashion Pendant"],
  },
  {
    name: "Maangtika",
    slug: "maangtika",
    image: "maangtika-set",
    subs: ["Maangtika", "Matha Patti", "Passa"],
  },
  {
    name: "Bangles",
    slug: "bangles",
    image: "bangles-kundan",
    subs: ["Kundan Bangles", "Antique Bangles", "Kada"],
  },
];

// [name, image, price, salePrice, category slug, subcategory, craftsmanship, occasion[], colors[], metal, stone, stoneColor, bestseller, newArrival, stock, returnable]
const P = (...a) => a;
const productRows = [
  P(
    "Antique Kasu Lakshmi Haram",
    "lakshmi-kasu-haram",
    6499,
    4899,
    "god-jewellery",
    "Lakshmi Haram",
    "Temple",
    ["Pooja", "Wedding"],
    ["Gold"],
    "Gold Plated",
    "Ruby",
    "Red",
    true,
    false,
    14,
    true,
  ),
  P(
    "Temple Lakshmi Kasu Mala",
    "antique-necklace",
    5299,
    0,
    "god-jewellery",
    "Kasu Mala",
    "Temple",
    ["Pooja", "Festive"],
    ["Gold", "Antique"],
    "Gold Plated",
    "Emerald",
    "Green",
    false,
    true,
    20,
    true,
  ),
  P(
    "Lord Ganesha Gold Pendant",
    "ganesha-pendant",
    1899,
    1499,
    "god-jewellery",
    "Deity Pendant",
    "Handcrafted",
    ["Pooja", "Daily Wear"],
    ["Gold"],
    "Gold Plated",
    "Cubic Zirconia",
    "White",
    true,
    false,
    40,
    true,
  ),
  P(
    "Krishna Flute Peacock Pendant",
    "krishna-flute",
    1299,
    0,
    "god-jewellery",
    "Deity Pendant",
    "Handcrafted",
    ["Pooja", "Daily Wear"],
    ["Gold", "Blue"],
    "Gold Plated",
    "Cubic Zirconia",
    "White",
    true,
    true,
    30,
    true,
  ),
  P(
    "Krishna Divine Hands Idol Pendant",
    "krishna-hands",
    1599,
    0,
    "god-jewellery",
    "Deity Pendant",
    "Handcrafted",
    ["Pooja"],
    ["Gold"],
    "Gold Plated",
    "",
    "",
    false,
    false,
    18,
    true,
  ),
  P(
    "Bharatnatyam Temple Vaddanam",
    "vaddanam-waist",
    7999,
    5999,
    "bharatnatyam-jewellery",
    "Vaddanam",
    "Temple",
    ["Bharatnatyam", "Wedding"],
    ["Gold", "Maroon"],
    "Gold Plated",
    "Ruby",
    "Red",
    true,
    false,
    9,
    false,
  ),
  P(
    "Bharatnatyam Pearl Ruby Full Set",
    "pearl-haram-strand",
    9499,
    7499,
    "bharatnatyam-jewellery",
    "Full Set",
    "Handcrafted",
    ["Bharatnatyam"],
    ["Gold", "Red"],
    "Gold Plated",
    "Pearl",
    "White",
    true,
    true,
    7,
    false,
  ),
  P(
    "Bharatnatyam Maangtika & Passa Set",
    "maangtika-set",
    2499,
    0,
    "bharatnatyam-jewellery",
    "Full Set",
    "Temple",
    ["Bharatnatyam"],
    ["Gold", "Red"],
    "Gold Plated",
    "Ruby",
    "Red",
    false,
    false,
    16,
    true,
  ),
  P(
    "Nrityam Kemp Necklace",
    "temple-necklace",
    4599,
    3499,
    "bharatnatyam-jewellery",
    "Full Set",
    "Temple",
    ["Bharatnatyam", "Festive"],
    ["Gold", "Red"],
    "Gold Plated",
    "Ruby",
    "Red",
    false,
    true,
    12,
    true,
  ),
  P(
    "Shahi Dwar Mohini Choker Set",
    "pink-choker",
    3399,
    2039,
    "jadau-kundan-jewellery",
    "Kundan Choker",
    "Kundan",
    ["Wedding", "Festive"],
    ["Gold", "Pink"],
    "Gold Plated",
    "Kundan",
    "Pink",
    true,
    true,
    25,
    true,
  ),
  P(
    "Jadau Kundan Bridal Choker",
    "gold-choker-drops",
    5799,
    4599,
    "jadau-kundan-jewellery",
    "Kundan Choker",
    "Jadau",
    ["Wedding"],
    ["Gold"],
    "Gold Plated",
    "Kundan",
    "White",
    true,
    false,
    11,
    true,
  ),
  P(
    "Polki Kundan Necklace & Earring Set",
    "necklace-earring-set",
    6899,
    0,
    "jadau-kundan-jewellery",
    "Kundan Set",
    "Jadau",
    ["Wedding", "Party"],
    ["Gold", "Green"],
    "Gold Plated",
    "Kundan",
    "Green",
    false,
    true,
    8,
    true,
  ),
  P(
    "Kundan Emerald Drop Choker",
    "choker-black-bead",
    4299,
    3299,
    "jadau-kundan-jewellery",
    "Kundan Choker",
    "Kundan",
    ["Festive", "Party"],
    ["Gold", "Green"],
    "Gold Plated",
    "Emerald",
    "Green",
    false,
    false,
    15,
    true,
  ),
  P(
    "Varalakshmi Kalasam Jewellery Set",
    "lakshmi-kasu-haram",
    5999,
    4499,
    "varalakshmi-items",
    "Jewellery Set",
    "Temple",
    ["Pooja", "Festive"],
    ["Gold", "Red"],
    "Gold Plated",
    "Ruby",
    "Red",
    true,
    false,
    10,
    true,
  ),
  P(
    "Varalakshmi Goddess Kasu Necklace",
    "temple-necklace",
    3799,
    0,
    "varalakshmi-items",
    "Pooja Set",
    "Temple",
    ["Pooja"],
    ["Gold"],
    "Gold Plated",
    "Ruby",
    "Red",
    false,
    true,
    22,
    true,
  ),
  P(
    "Goddess Pooja Antique Haram",
    "antique-necklace",
    4199,
    3199,
    "varalakshmi-items",
    "Pooja Set",
    "Antique",
    ["Pooja", "Festive"],
    ["Gold", "Antique"],
    "Gold Plated",
    "",
    "",
    false,
    false,
    19,
    true,
  ),
  P(
    "Varalakshmi Vratham Gold Bangles",
    "bangles-pair-red",
    2199,
    0,
    "varalakshmi-items",
    "Jewellery Set",
    "Kundan",
    ["Pooja"],
    ["Gold", "Red"],
    "Gold Plated",
    "Ruby",
    "Red",
    false,
    false,
    26,
    true,
  ),
  P(
    "Antique Necklace 241554",
    "antique-necklace",
    1423,
    0,
    "necklaces",
    "Necklace",
    "Antique",
    ["Festive", "Daily Wear"],
    ["Gold", "Antique"],
    "Gold Plated",
    "",
    "",
    true,
    true,
    60,
    true,
  ),
  P(
    "Gold Necklace 241555",
    "gold-choker-drops",
    1799,
    0,
    "necklaces",
    "Necklace",
    "Handcrafted",
    ["Festive", "Party"],
    ["Gold"],
    "Gold Plated",
    "",
    "",
    true,
    false,
    45,
    true,
  ),
  P(
    "Kemp Ruby Long Haram",
    "lakshmi-kasu-haram",
    4899,
    3899,
    "necklaces",
    "Long Haram",
    "Temple",
    ["Wedding", "Festive"],
    ["Gold", "Red"],
    "Gold Plated",
    "Ruby",
    "Red",
    true,
    false,
    13,
    true,
  ),
  P(
    "Pearl Mango Mala Haram",
    "pearl-haram-strand",
    3299,
    0,
    "necklaces",
    "Long Haram",
    "Handcrafted",
    ["Wedding", "Festive"],
    ["Gold", "White"],
    "Gold Plated",
    "Pearl",
    "White",
    false,
    true,
    17,
    true,
  ),
  P(
    "American Diamond Necklace",
    "diamond-necklace",
    2899,
    2299,
    "necklaces",
    "Necklace",
    "Handcrafted",
    ["Party", "Wedding"],
    ["Silver", "White"],
    "Silver Plated",
    "Cubic Zirconia",
    "White",
    true,
    true,
    21,
    true,
  ),
  P(
    "Rani Haar Pink Pendant Set",
    "pink-choker",
    3999,
    0,
    "necklaces",
    "Pendant Set",
    "Kundan",
    ["Wedding"],
    ["Gold", "Pink"],
    "Gold Plated",
    "Kundan",
    "Pink",
    false,
    false,
    12,
    true,
  ),
  P(
    "Temple Coin Choker",
    "temple-necklace",
    2599,
    1999,
    "necklaces",
    "Choker",
    "Temple",
    ["Festive", "Daily Wear"],
    ["Gold"],
    "Gold Plated",
    "",
    "",
    false,
    false,
    33,
    true,
  ),
  P(
    "Black Bead Gold Choker",
    "choker-black-bead",
    2199,
    0,
    "necklaces",
    "Choker",
    "Handcrafted",
    ["Daily Wear", "Party"],
    ["Gold", "Black"],
    "Gold Plated",
    "Black Onyx",
    "Black",
    false,
    true,
    28,
    true,
  ),
  P(
    "Antique Earring 142501",
    "jhumka-pair",
    1423,
    0,
    "earrings",
    "Jhumkas",
    "Antique",
    ["Festive", "Wedding"],
    ["Gold", "Red", "Green"],
    "Gold Plated",
    "Ruby",
    "Pink",
    true,
    true,
    50,
    true,
  ),
  P(
    "Ruby Emerald Temple Jhumkas",
    "jhumka-pair",
    1999,
    1599,
    "earrings",
    "Jhumkas",
    "Temple",
    ["Festive", "Wedding"],
    ["Gold", "Red", "Green"],
    "Gold Plated",
    "Ruby",
    "Red",
    true,
    false,
    38,
    true,
  ),
  P(
    "Kundan Chandbali Earrings",
    "chandbali-promo",
    2299,
    0,
    "earrings",
    "Chandbali",
    "Kundan",
    ["Wedding", "Party"],
    ["Gold", "Green"],
    "Gold Plated",
    "Kundan",
    "Green",
    true,
    true,
    24,
    true,
  ),
  P(
    "Pearl Drop Antique Earrings",
    "model-earring",
    1699,
    1299,
    "earrings",
    "Drops",
    "Antique",
    ["Festive"],
    ["Gold", "White"],
    "Gold Plated",
    "Pearl",
    "White",
    false,
    false,
    30,
    true,
  ),
  P(
    "Gold Peacock Stud Earrings",
    "choker-black-bead",
    899,
    0,
    "earrings",
    "Studs",
    "Handcrafted",
    ["Daily Wear"],
    ["Gold"],
    "Gold Plated",
    "",
    "",
    false,
    false,
    70,
    true,
  ),
  P(
    "Ganesha Teardrop Diamond Pendant",
    "ganesha-pendant",
    2199,
    1699,
    "pendants",
    "Deity Pendant",
    "Handcrafted",
    ["Pooja", "Daily Wear"],
    ["Gold", "White"],
    "Gold Plated",
    "Cubic Zirconia",
    "White",
    true,
    true,
    35,
    true,
  ),
  P(
    "Krishna Flute Pendant with Chain",
    "krishna-flute",
    1499,
    0,
    "pendants",
    "Deity Pendant",
    "Handcrafted",
    ["Daily Wear", "Pooja"],
    ["Gold", "Blue"],
    "Gold Plated",
    "Sapphire",
    "Blue",
    true,
    false,
    42,
    true,
  ),
  P(
    "Peacock Feather Gold Pendant",
    "krishna-hands",
    1199,
    0,
    "pendants",
    "Fashion Pendant",
    "Handcrafted",
    ["Daily Wear"],
    ["Gold"],
    "Gold Plated",
    "",
    "",
    false,
    true,
    46,
    true,
  ),
  P(
    "Solitaire Look Teardrop Pendant",
    "diamond-necklace",
    1599,
    1199,
    "pendants",
    "Diamond Look",
    "Handcrafted",
    ["Party", "Daily Wear"],
    ["Silver", "White"],
    "Silver Plated",
    "Cubic Zirconia",
    "White",
    false,
    false,
    27,
    true,
  ),
  P(
    "Temple Maangtika 142600",
    "maangtika-set",
    1299,
    0,
    "maangtika",
    "Maangtika",
    "Temple",
    ["Bharatnatyam", "Wedding"],
    ["Gold", "Red"],
    "Gold Plated",
    "Ruby",
    "Red",
    true,
    true,
    32,
    true,
  ),
  P(
    "Kundan Matha Patti",
    "maangtika-set",
    2499,
    1899,
    "maangtika",
    "Matha Patti",
    "Kundan",
    ["Wedding"],
    ["Gold", "Pink"],
    "Gold Plated",
    "Kundan",
    "Pink",
    true,
    false,
    14,
    true,
  ),
  P(
    "Pearl Passa Bridal Set",
    "pearl-haram-strand",
    1899,
    0,
    "maangtika",
    "Passa",
    "Handcrafted",
    ["Wedding"],
    ["Gold", "White"],
    "Gold Plated",
    "Pearl",
    "White",
    false,
    false,
    19,
    true,
  ),
  P(
    "Kundan Kada Bangles (Set of 2)",
    "bangles-kundan",
    2999,
    2399,
    "bangles",
    "Kundan Bangles",
    "Kundan",
    ["Wedding", "Festive"],
    ["Gold", "Red", "Green"],
    "Gold Plated",
    "Kundan",
    "Green",
    true,
    true,
    23,
    true,
  ),
  P(
    "Antique Ruby Bangles (Set of 2)",
    "bangles-pair-red",
    2399,
    0,
    "bangles",
    "Antique Bangles",
    "Antique",
    ["Festive", "Wedding"],
    ["Gold", "Red"],
    "Gold Plated",
    "Ruby",
    "Red",
    true,
    false,
    29,
    true,
  ),
  P(
    "Black Bead Temple Bangles (Set of 2)",
    "bangles-pair-dark",
    2699,
    2099,
    "bangles",
    "Antique Bangles",
    "Temple",
    ["Festive"],
    ["Gold", "Black"],
    "Gold Plated",
    "Black Onyx",
    "Black",
    false,
    true,
    18,
    true,
  ),
  P(
    "Gold Plated Kada",
    "bangles-kundan",
    1599,
    0,
    "bangles",
    "Kada",
    "Handcrafted",
    ["Daily Wear", "Party"],
    ["Gold"],
    "Gold Plated",
    "",
    "",
    false,
    false,
    0,
    true,
  ),
  P(
    "New Season Antique Choker 241560",
    "pink-choker",
    2899,
    0,
    "new-arrivals",
    "Choker",
    "Antique",
    ["Festive"],
    ["Gold", "Pink"],
    "Gold Plated",
    "Kundan",
    "Pink",
    true,
    true,
    20,
    true,
  ),
  P(
    "New Season Temple Jhumka 241561",
    "jhumka-pair",
    1699,
    0,
    "new-arrivals",
    "Jhumkas",
    "Temple",
    ["Festive"],
    ["Gold", "Green"],
    "Gold Plated",
    "Emerald",
    "Green",
    false,
    true,
    20,
    true,
  ),
  P(
    "New Season Kemp Necklace 241562",
    "temple-necklace",
    3499,
    2799,
    "new-arrivals",
    "Necklace",
    "Temple",
    ["Wedding"],
    ["Gold", "Red"],
    "Gold Plated",
    "Ruby",
    "Red",
    false,
    true,
    15,
    true,
  ),
];

const lorem = (name, cat) =>
  `Omkari Fashions Jewellery presents ${name}, an exquisite piece from our ${cat} range crafted to enhance your traditional and festive looks. Featuring intricate floral motifs, timeless craftsmanship and elegant detailing, this piece is designed to make a statement. Pair it with ethnic attire to add a touch of elegance to every occasion.`;

const faqs = [
  [
    "Is the jewellery real gold?",
    "Our designs are gold plated on premium quality brass with a lasting finish, giving you the look of traditional gold jewellery at an accessible price.",
  ],
  [
    "How long does delivery take?",
    "Orders are usually delivered within 4-7 working days. You can check the estimated date on any product page by entering your pincode.",
  ],
  [
    "Can I return or exchange a product?",
    "Yes. Eligible products can be returned within the return window after delivery. Damaged or wrong products need a photo as proof.",
  ],
  [
    "How do I care for my jewellery?",
    "Keep it dry, store it in the pouch provided, and apply perfume before wearing jewellery.",
  ],
  [
    "Do you offer Cash on Delivery?",
    "Yes, Cash on Delivery is available on all orders. For online payments we accept UPI, cards and net banking via Razorpay.",
  ],
  [
    "Can I visit your store?",
    "Absolutely. Walk in to experience our full collection. Check the Store Locator for our address and timings.",
  ],
];

const testimonials = [
  [
    "Oindrila Saha",
    "Absolutely loved my jewellery! The design is elegant, delicate, and looks even more beautiful when worn.",
    "avatar-1",
  ],
  [
    "Lakshmi Prasanna",
    "The Bharatnatyam set was perfect for my daughter's arangetram. Finish and quality were beyond expectations.",
    "model-necklace",
  ],
  [
    "Divya Reddy",
    "Ordered the kundan choker for a wedding. Received many compliments and delivery was quick.",
    "model-saree",
  ],
  [
    "Sravani K",
    "Lovely temple jewellery collection. Neatly packed and exactly like the photos.",
    "model-mangalsutra",
  ],
  [
    "Meena Iyer",
    "Best place for Varalakshmi pooja jewellery. Genuine service and beautiful designs.",
    "model-earring",
  ],
];

const cms = [
  {
    key: "about",
    title: "What is OMKARI FASHIONS?",
    subtitle: "A Legacy Built On Trust",
    image: img("model-necklace"),
    content:
      "For generations, Omkari Fashions has been bringing together the beauty of traditional Indian jewellery and the elegance of modern celebrations from God Jewellery and South Indian traditional designs to bridal and festive collections.\n\nEvery piece is thoughtfully chosen to celebrate the occasions that matter most for us, jewellery is more than accessory. It carries emotion and memories. Our commitment has always been simple quality, value and genuine customer service.",
    items: [
      { title: "Rooted In Tradition" },
      { title: "Built On Trust" },
      { title: "Made For Moments" },
    ],
  },
  {
    key: "about-values",
    title: "What we stand for",
    subtitle:
      "Omkari Fashions – Every piece reflects our commitment to quality, elegance, and timeless style.",
    items: [
      {
        title: "Craftsmanship",
        text: "Every design showcases artistry, precision, and a passion for excellence.",
      },
      {
        title: "Elegance",
        text: "Our jewellery is designed to celebrate timeless traditions with a modern touch.",
      },
      {
        title: "Trust",
        text: "We believe in exceptional quality, value, and customer satisfaction at every step.",
      },
    ],
  },
  {
    key: "contact",
    title: "Contact Us",
    subtitle:
      "Get in touch with us today to discover more about the elegant and captivating world of Omkari Fashions.",
    content:
      "Please contact us on the above-mentioned number via WhatsApp only for order-related queries.\n\nFor general enquiries, you can also write to us through our website or email.\n\nWe are committed to providing you with a seamless shopping experience and exceptional customer service. Whether you have a question about an order, product, or our collection, our team is always happy to assist you.\n\nExplore our beautiful collection and discover jewellery that adds elegance and charm to every occasion.",
  },
  {
    key: "home-about",
    title: "About Omkari Fashions",
    subtitle: "The Signature",
    image: img("chandbali-promo"),
    content:
      "Designed for modern celebrations, our signature necklaces combine traditional floral artistry with lightweight comfort. Each piece is intricately hand-woven by masters of floral design, ensuring that your special occasions remain comfortable, authentic, and naturally radiant.",
    items: [
      {
        title:
          "Timeless Gold Jewellery, Crafted to Make Every Moment Memorable",
      },
      {
        title: "100% HANDCRAFTED",
        text: "With Exceptional Craftsmanship & Finest Gold",
      },
    ],
  },
  {
    key: "best-sellers",
    title: "Best Sellers",
    items: [
      { image: img("model-saree") },
      { image: img("model-necklace") },
      { image: img("model-earring") },
      { image: img("model-mangalsutra") },
      { image: img("model-rings") },
    ],
  },
  {
    key: "walkin",
    title: "Walk - In Customer Experience",
    items: [
      {
        title: "Bridal fitting",
        image: img("model-rings"),
        text: "Trying the Kundan set",
      },
      {
        title: "Festive shopping",
        image: img("model-saree"),
        text: "Choosing temple jewellery",
      },
      {
        title: "Family visit",
        image: img("model-earring"),
        text: "Pearl and ruby sets",
      },
      {
        title: "Bharatnatyam shopping",
        image: img("model-necklace"),
        text: "Dance jewellery",
      },
    ],
  },
  {
    key: "store-locator",
    title: "Store Locator",
    content:
      "Visit us at our store to experience the full Omkari Fashions collection.\n\nSupport hours: Mon to Sat (10:00 AM - 8:00 PM).\nPhone / WhatsApp: 9177447021, 9441090785\nEmail: omkarifashions1@gmail.com\n\nUpdate the store address from Admin > Settings.",
  },
  {
    key: "privacy-policy",
    title: "Privacy Policy",
    content:
      "We respect your privacy. We collect only the information needed to process your orders, provide support and improve our service: your name, contact details, delivery address and order history.\n\nWe never sell your personal information. Payment details are processed securely by Razorpay and are never stored on our servers.\n\nYou may contact us at any time to update or delete your account information.",
  },
  {
    key: "terms-of-use",
    title: "Terms of Use",
    content:
      "By using this website you agree to these terms. Product images are for illustration and slight variations in colour may occur. Prices and availability may change without notice.\n\nOrders are subject to acceptance and stock availability. We reserve the right to cancel orders in case of pricing errors or suspected misuse.",
  },
  {
    key: "shipping-policy",
    title: "Shipping Policy",
    content:
      "We ship across India. Orders are dispatched within 1-2 working days and are usually delivered in 4-7 working days.\n\nShipping charges (if any) are shown at checkout. Orders above the free shipping value ship free. You will receive tracking details once your order is shipped.",
  },
  {
    key: "return-and-refund-policy",
    title: "Return and Refund Policy",
    content:
      "Eligible products can be returned within the return window shown on the product and order page, counted from the delivery date. Products must be unused and in original packaging.\n\nFor damaged or wrong products please upload clear photos while raising the return.\n\nOnline payments are refunded to the original payment account. For Cash on Delivery orders the refund is sent to the UPI ID provided by you. Refunds are processed after we receive and inspect the item.",
  },
];

async function run() {
  await mongoose.connect(env.mongoUri);
  console.log("Connected. Seeding catalogue data...");
  await Promise.all(
    [
      Category,
      Collection,
      Product,
      Banner,
      FAQ,
      Testimonial,
      CMSPage,
      Coupon,
    ].map((m) => m.deleteMany({})),
  );

  const cats = {};
  let order = 0;
  for (const c of categories) {
    // eslint-disable-next-line no-await-in-loop
    cats[c.slug] = await Category.create({
      name: c.name,
      slug: c.slug,
      image: img(c.image),
      description: `${c.name} - traditional Indian jewellery from Omkari Fashions`,
      subcategories: c.subs,
      showInCircles: Boolean(c.circle),
      showOnHome: Boolean(c.home),
      homeTitle: c.name,
      displayOrder: (order += 1),
    });
  }

  let n = 241500;
  const products = [];
  for (const r of productRows) {
    const [
      name,
      image,
      price,
      salePrice,
      cat,
      sub,
      craft,
      occasion,
      colors,
      metal,
      stone,
      stoneColor,
      best,
      isNew,
      stock,
      ret,
    ] = r;
    n += 1;
    const extra = ["antique-necklace", "temple-necklace"].includes(image)
      ? "necklace-earring-set"
      : "gold-choker-drops";
    // eslint-disable-next-line no-await-in-loop
    products.push(
      await Product.create({
        name,
        slug: `${slugify(name)}`,
        sku: `OMK-${n}`,
        price,
        salePrice,
        stock,
        category: cats[cat]._id,
        subcategory: sub,
        craftsmanship: craft,
        occasion,
        colors,
        metalType: metal,
        stoneType: stone,
        stoneColor,
        isBestseller: best,
        isNewArrival: isNew,
        isReturnable: ret,
        images: [{ url: img(image) }, { url: img(extra) }, { url: img(image) }],
        shortDescription: `${name} - ${craft} craftsmanship`,
        description: lorem(name, categories.find((c) => c.slug === cat).name),
        tags: [...occasion, craft, sub, metal].map((t) => t.toLowerCase()),
        specifications: {
          size: "Adjustable",
          colour: colors.join(", "),
          designNo: String(n),
          baseMetal: "Brass",
          countryOfOrigin: "India",
          brand: "Omkari Fashions",
        },
        ratingAvg: best ? 4.9 : 4.6,
        ratingCount: best ? 12 : 4,
        soldCount: best ? 40 + (n % 30) : n % 12,
      }),
    );
  }

  const pick = (pred) => products.filter(pred).map((p) => p._id);
  await Collection.create([
    {
      title: "Bridal Collection",
      slug: "bridal-collection",
      description: "Statement jewellery for the bride",
      image: img("gold-choker-drops"),
      displayOrder: 1,
      products: pick((p) => p.occasion.includes("Wedding")),
    },
    {
      title: "Festive Edit",
      slug: "festive-edit",
      description: "Sparkle through every festival",
      image: img("jhumka-pair"),
      displayOrder: 2,
      products: pick((p) => p.occasion.includes("Festive")),
    },
    {
      title: "Temple Classics",
      slug: "temple-classics",
      description: "Timeless South Indian temple jewellery",
      image: img("lakshmi-kasu-haram"),
      displayOrder: 3,
      products: pick((p) => p.craftsmanship === "Temple"),
    },
    {
      title: "Everyday Elegance",
      slug: "everyday-elegance",
      description: "Light pieces for daily wear",
      image: img("krishna-flute"),
      displayOrder: 4,
      products: pick((p) => p.occasion.includes("Daily Wear")),
    },
  ]);
  for (const col of await Collection.find())
    await Product.updateMany(
      { _id: { $in: col.products } },
      { $addToSet: { collections: col._id } },
    );

  await Banner.create([
    {
      title: "God Jewellery",
      image: "/uploads/seed/banner-god-jewellery.jpg",
      mobileImage: "/uploads/seed/banner-god-mobile.jpg",
      buttonText: "Shop Now",
      buttonUrl: "/category/god-jewellery",
      showText: false,
      displayOrder: 1,
    },
    {
      title: "Bharatnatyam Set",
      image: "/uploads/seed/banner-bharatnatyam.jpg",
      mobileImage: "/uploads/seed/banner-bharat-mobile.jpg",
      buttonText: "Shop Now",
      buttonUrl: "/category/bharatnatyam-jewellery",
      showText: false,
      displayOrder: 2,
    },
  ]);
  await FAQ.create(
    faqs.map(([question, answer], i) => ({
      question,
      answer,
      displayOrder: i,
    })),
  );
  await Testimonial.create(
    testimonials.map(([name, message, im], i) => ({
      name,
      message,
      image: img(im),
      displayOrder: i,
    })),
  );
  await CMSPage.create(cms);
  await Coupon.create([
    {
      code: "WELCOME10",
      description: "10% off your order (max Rs. 500)",
      type: "percent",
      value: 10,
      maxDiscount: 500,
      minOrderValue: 999,
    },
    {
      code: "FESTIVE200",
      description: "Flat Rs. 200 off on orders above Rs. 2,500",
      type: "flat",
      value: 200,
      minOrderValue: 2500,
    },
  ]);

  await SiteSettings.findOneAndUpdate(
    { key: "main" },
    { $setOnInsert: { key: "main" } },
    { upsert: true, setDefaultsOnInsert: true },
  );
  const admin = await User.findOne({ email: env.admin.email.toLowerCase() });
  if (!admin) {
    await User.create({
      name: env.admin.name,
      email: env.admin.email,
      phone: "9000000000",
      password: env.admin.password,
      role: "admin",
    });
    console.log(`Admin created: ${env.admin.email} / ${env.admin.password}`);
  } else console.log(`Admin exists: ${admin.email}`);

  console.log(
    `Seeded ${Object.keys(cats).length} categories, ${products.length} products.`,
  );
  await mongoose.disconnect();
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
